.catalog:
  name: "ChinaLife monitoring"
  version: "v0.8.0"
  questions:
    - variable: "CADVISOR_PORT"
      label: "cadvisor port"
      description: "cadvisor port"
      type: "string"
      default: "9101"
      required: true
    - variable: NODE_EXPORTER_PORT
      label: "node exporter port"
      description: "node exporter port"
      required: true
      type: "string"
      default: "9100"
    - variable: RANCHER_HEALTH_EXPORTER_PORT
      label: "rancher health exporter port"
      description: "rancher health exporter port"
      required: true
      type: "string"
      default: "9173"
    - variable: CADVISOR_ARG
      label: "cadvisor extension parameters"
      description: "cadvisor extension parameters"
      required: true
      type: "string"
      default: "--housekeeping_interval=10s "
    - variable: CADVISOR_IMAGES
      label: "cadvisor images"
      description: "cadvisor images"
      required: true
      type: "string"
      default: "10.30.12.7/rancher/cadvisor:v0.33.0-1"
    - variable: NODE_EXPORTER_IMAGES
      label: "node exporter images"
      description: "node exporter images"
      required: true
      type: "string"
      default: "prom/node-exporter:v0.14.0"
    - variable: RANCHER_HEALTH_EXPORTER_IMAGES
      label: "rancher health exporter images"
      description: "rancher health exporter images"
      required: true
      type: "string"
      default: "maiwj/rancher1.x-exporter:2.3.1"

rancher-health-exporter:
  scale: 1
  health_check:
    port: 9173
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000