{{- if .Values.pspEnabled }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    app: {{ template "app.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    chart: {{ template "app.version" . }}
  name: {{ template "app.fullname" . }}
rules:
  - apiGroups:
    - policy
    resources:
    - podsecuritypolicies
    resourceNames:
    - {{ template "app.fullname" . }}-psp
    verbs:
    - use
{{- end -}}
