apiVersion: v1
description: From Prometheus Blackbox Exporter Chart 4.1.0
name: exporter-blackbox
version: 0.0.1
appVersion: 0.16.0
home: https://github.com/prometheus/blackbox_exporter
sources:
  - https://github.com/prometheus/blackbox_exporter
keywords:
  - prometheus
  - blackbox
  - monitoring
maintainers:
  - name: michelia
    email: michelia@rancher.com
